[tool.poetry]
name = "elnath"
version = "0.1.0"
description = "Homepage y sistema de administración para CNTX"
authors = ["Ricardo Cisterna <r.cisternasantos@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1"

[tool.poetry.dev-dependencies]
pylint = "^2.1"
flake8 = "^3.5"
